apiVersion: apps/v1
kind: Deployment
metadata:
  name: sirh-backend
  labels:
    app: sirh-backend
    type: backend
spec:
  selector:
    matchLabels:
      app: sirh-backend
      type: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sirh-backend
        type: backend
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: sirh-backend
          image: brims15/sirh:0.0.1-SNAPSHOT
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "2"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 9099
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: ORACLEHOSTSIRH
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-sirh
                  key: default.oracle-instance-host-sirh
            - name: ORACLEPORTSIRH
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-sirh
                  key: default.oracle-instance-port-sirh
            - name: ORACLEUSERSIRH
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-sirh
                  key: default.oracle-instance-user-sirh
            - name: ORACLEPASSWORDSIRH
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-sirh
                  key: password
            - name: ORACLEHOSTPG
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-parametrageglobal
                  key: default.oracle-instance-host-pg
            - name: ORACLEPORTPG
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-parametrageglobal
                  key: default.oracle-instance-port-pg
            - name: ORACLEUSERPG
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-parametrageglobal
                  key: default.oracle-instance-user-pg
            - name: ORACLEPASSWORDPG
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-paramglobal
                  key: password  
            
            