apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudiant-back-deployment
  labels:
    app: etudiant-back-deployment
    type: backend
spec:
  selector:
    matchLabels:
      app: etudiant-backend
      type: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etudiant-backend
        type: backend
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: etudiant-backend
          image: brims15/backendgestionetudiant:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "128Mi"
              cpu: "256m"
            limits:
              memory: "256Mi"
              cpu: "528m"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: default.mysql-instance-host
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: default.mysql-instance-port
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: default.mysql-instance-user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-instance-password
                  key: password
            
      