apiVersion: v1
kind: Service
metadata:
  name: service-etudiant
spec:
  selector:
    app: etudiant-backend
    type: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-backend
   
