---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
spec:
  selector:
    app: gestionstock-backend
    type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-backend
   
