apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-front-deployment
  labels:
    app: admin-front
    type: front
spec:
  selector:
    matchLabels:
      app: admin-front
      type: front
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin-front    
        type: front
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: admin-front
          image: brims15/frontadmine:106
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "700Mi"
              cpu: "500m"
            limits:
              memory: "3Gi"
              cpu: "5"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          env: 
            - name: KEYCLOAKHOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: default.host-keycloak
            - name: KEYCLOAKPORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: default.port-keycloak
            - name: KEYCLOAKUSER
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: default.user-keycloak
            - name: KEYCLOAKPASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-instance-password
                  key: password
          
          
          
      