apiVersion: v1
data:
  default.oracle-instance-host-comptabilite: 192.168.2.38
  default.oracle-instance-port-comptabilite: "1521"
  default.oracle-instance-user-comptabilite: comptabilite
kind: ConfigMap
metadata:
  name: oracle-config-comptabilite
  namespace: default
