apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-finance
  labels:
    app: front-finance
    type: front
spec:
  selector:
    matchLabels:
      app: front-finance
      type: front
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-finance    
        type: front
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: front-finance
          image: brims15/front-gestion-finance:1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW      
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "2"         
              #---------------------------------#
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
      
          
          
      