apiVersion: apps/v1
kind: Deployment
metadata:
  name: paramglob-back-deployment
  labels:
    app: paramglob-backend
    type: backend
spec:
  selector:
    matchLabels:
      app: paramglob-backend
      type: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: paramglob-backend
        type: backend
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: paramglob-backend
          image: brims15/parametrageglobal:0.0.1-SNAPSHOT
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "2"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 8087
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: ORACLEHOST
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-pg
                  key: default.oracle-instance-host-pg
            - name: ORACLEPORT
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-pg
                  key: default.oracle-instance-port-pg
            - name: ORACLEUSER
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-pg
                  key: default.oracle-instance-user-pg
            - name: ORACLEPASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-pg
                  key: password
            
      
