apiVersion: v1
data:
  default.oracle-instance-host-rp: 192.168.2.38
  default.oracle-instance-port-rp: "1521"
  default.oracle-instance-user-rp: risquesprofessionnels
kind: ConfigMap
metadata:
  name: oracle-config-rp
  namespace: default
