---
apiVersion: v1
kind: Service
metadata:
  name: service-etudiantfront
spec:
  selector:
    app: etudiant-front
    type: front
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      name: http-front
      nodePort: 30201 
      
   
