apiVersion: v1
data:
  default.oracle-instance-host-cotisation: 192.168.2.38
  default.oracle-instance-port-cotisation: "1521"
  default.oracle-instance-user-cotisation: cotisation
kind: ConfigMap
metadata:

  name: oracle-config-cotisation
  namespace: default
