apiVersion: v1
data:
  default.oracle-instance-host-pg: 158.69.27.218
  default.oracle-instance-port-pg: "1521"
  default.oracle-instance-user-pg: parametrageglobal
kind: ConfigMap
metadata:

  name: oracle-config-parametrageglobal
  namespace: default
