---
apiVersion: v1
kind: Service
metadata:
  name: service-front
spec:
  selector:
    app: company-front
    type: front
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      name: http-front
      nodePort: 30200 
      
   
