apiVersion: v1
data:
  default.oracle-instance-host-tresorerie: 158.69.27.218
  default.oracle-instance-port-tresorerie: "1521"
  default.oracle-instance-user-tresorerie: tresorerie
kind: ConfigMap
metadata:

  name: oracle-config-tresorerie
  namespace: default
