apiVersion: v1
kind: Service
metadata:
  name: service-mandat
spec:
  selector:
    app: mandat-backend
    type: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
      name: http-backend
    
