apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-backend
  labels:
    app: pf-backend
    type: backend
spec:
  selector:
    matchLabels:
      app: pf-backend
      type: backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pf-backend
        type: backend
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: pf-backend
          image: brims15/prestationsfamiliales:0.0.1-SNAPSHOT
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "2"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 8085
              protocol: TCP
          imagePullPolicy: Always
          env:
            - name: ORACLEHOSTPF
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-pf
                  key: default.oracle-instance-host-pf
            - name: ORACLEPORTPF
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-pf
                  key: default.oracle-instance-port-pf
            - name: ORACLEUSERPF
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-pf
                  key: default.oracle-instance-user-pf
            - name: ORACLEPASSWORDPF
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-pf
                  key: password
            - name: ORACLEHOSTFO
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-fo
                  key: default.oracle-instance-host-fo
            - name: ORACLEPORTFO
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-fo
                  key: default.oracle-instance-port-fo
            - name: ORACLEUSERFO
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-fo
                  key: default.oracle-instance-user-fo
            - name: ORACLEPASSWORDFO
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-fo
                  key: password
            - name: ORACLEHOSTIMM
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-imm
                  key: default.oracle-instance-host-imm
            - name: ORACLEPORTIMM
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-imm
                  key: default.oracle-instance-port-imm
            - name: ORACLEUSERIMM
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-imm
                  key: default.oracle-instance-user-imm
            - name: ORACLEPASSWORDIMM
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-imm
                  key: password      
            
            - name: ORACLEHOSTTRACACTION
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-tracaction
                  key: default.oracle-instance-host-tracaction
            - name: ORACLEPORTTRACACTION
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-tracaction
                  key: default.oracle-instance-port-tracaction
            - name: ORACLEUSERTRACACTION
              valueFrom:
                configMapKeyRef:
                  name: oracle-config-tracaction
                  key: default.oracle-instance-user-tracaction
            - name: ORACLEPASSWORDTRACACTION
              valueFrom:
                secretKeyRef:
                  name: oracle-instance-password-tracaction
                  key: password
      
