apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-metier
  labels:
    app: front-metier
    type: front
spec:
  selector:
    matchLabels:
      app: front-metier
      type: front
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front-metier    
        type: front
    spec:
      imagePullSecrets:
       - name: regcred
      containers:
        - name: front-metier
          image: brims15/frontmetier:1
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            requests:
              memory: "5348Mi"
              cpu: "900m"
            limits:
              memory: "11Gi"
              cpu: "8"
              #---------------------------------#
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          
          
      